/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE aulaBaseService PLEASE EDIT ../aula.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Aula } from '../../domain/roomenta_db/aula';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Aula.service.ts
 */

/*
 * SCHEMA DB Aula
 *
	{
		capacity: {
			type: 'Integer'
		},
		name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		contains: {
			type: Schema.ObjectId,
			ref : "Sede"
		},
	}
 *
 */
@Injectable()
export class AulaBaseService {

    private aulaCollection: AngularFirestoreCollection<Aula>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.aulaCollection = afs.collection<Aula>('aula');
    }


    // CRUD METHODS

    /**
    * AulaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Aula): Promise<DocumentReference> {
        return this.aulaCollection.add(item);
    }

    /**
    * AulaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.aulaCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * AulaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Aula> {
        return this.afs.doc<Aula>('aula/' + id);
    }

    /**
    * AulaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Aula[]> {
        return this.afs.collection('aula').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Aula;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * AulaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Aula>, item: Aula): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
